import Link from "next/link";

const projects = [
  {title:"Classic Models Sales Dashboard",type:"POWER BI · FEATURED",desc:"Multi-page business intelligence dashboard analysing sales, profitability, product performance, customers and annual trends.",tools:["Power BI","Power Query","DAX","Data Modelling"],href:"/projects/classic-models",repo:"https://github.com/ayushszode/classic-models-sales-dashboard",image:"https://raw.githubusercontent.com/ayushszode/classic-models-sales-dashboard/main/sales-overview.png"},
  {title:"FP&A Financial Performance & Budget Variance Analysis",type:"FINANCIAL ANALYTICS · NEW",desc:"End-to-end FP&A project using a synthetic UK retail management-accounting dataset to analyse Actual vs Budget revenue, gross margin, operating costs, EBITDA and full-year forecast performance.",tools:["Excel","SQL","Python","FP&A"],href:"/projects/fpa-financial-performance-analysis",repo:"https://github.com/ayushszode/fpa-financial-performance-analysis",image:"https://raw.githubusercontent.com/ayushszode/fpa-financial-performance-analysis/main/images/executive_dashboard.png"},
  {title:"UK Labour Market Forecasting & Workforce Analytics",type:"MSC DISSERTATION · ONGOING",desc:"Official ONS labour-market data transformed into a reproducible forecasting workflow and interactive Streamlit analytics dashboard.",tools:["Python","Pandas","scikit-learn","Plotly","Streamlit"],href:"/projects/uk-labour-market"},
  {title:"Student Recruitment & Enrollment Conversion Analytics",type:"REAL BUSINESS ANALYTICS · ANONYMISED",desc:"Internship case study identifying demand, enrollment and conversion patterns from student enquiry data while protecting confidential information.",tools:["Excel","Data Cleaning","Funnel Analysis","Reporting"],href:"/projects/myedbuddy"},
  {title:"Amazon Prime Content Analysis",type:"PYTHON · EDA",desc:"Exploratory analysis of streaming catalogue data to understand content mix, release patterns and business-relevant trends.",tools:["Python","Pandas","Matplotlib","EDA"],repo:"https://github.com/ayushszode/amazon-prime-content-analysis"},
  {title:"Vote Ledger — Secure Blockchain E‑Voting",type:"RESEARCH · ML/AI",desc:"Research-led anomaly-detection concept combining blockchain, Isolation Forests, Autoencoders and federated-learning ideas.",tools:["Python","Blockchain","ML","Anomaly Detection"]}
];
const skills=[
  ["Data Analytics & BI","Power BI · Power Query · Advanced Excel · Tableau · DAX · KPI Reporting · Dashboard Design · Data Cleaning · Data Validation"],
  ["Financial & Commercial Analysis","Budget vs Actual · Variance Analysis · Gross Margin · EBITDA · Forecasting · Cost-driver Analysis · Management Reporting"],
  ["Programming & Databases","Python · Pandas · NumPy · SQL · Jupyter Notebook · Matplotlib · Plotly"],
  ["Machine Learning & AI","scikit-learn · Predictive Modelling · Forecasting · Classification · Anomaly Detection · Feature Engineering · Generative AI · LLMs"],
  ["Cloud & Tools","GitHub · Streamlit · Databricks · AWS Educate · Google Cloud AI · Vertex AI"]
];
const credentials=["IBM SkillsBuild Data Fundamentals","Databricks Fundamentals","AWS Educate Cloud Computing 101","Advanced Data Visualization Using Power BI","Google AI Essentials","Google Cloud: Prompt Design in Vertex AI"];

export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top"><b>AZ</b><span>Ayush Sanjay Zode<small>@ayushszode</small></span></a><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav></header>
<section className="hero" id="top"><div className="grid"/><div className="wrap heroGrid"><div><div className="available"><i/>Available for Data Analyst opportunities in the UK</div><p className="kicker">@ayushszode · Liverpool, UK</p><h1>Ayush Sanjay<br/>Zode</h1><h2>Data Analyst <span>|</span> Business Intelligence <span>|</span> Power BI <span>|</span> SQL <span>|</span> Python</h2><p className="lead">Turning complex data into clear, actionable business insights through analytics, dashboards, automation, financial analysis and predictive modelling.</p><div className="actions"><a className="btn" href="#projects">View Projects</a><a className="btn ghost" href="mailto:ayush.s.zode.uk@gmail.com?subject=Portfolio%20enquiry">Contact Me</a><a href="https://github.com/ayushszode" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/ayush-zode-b72020321" target="_blank">LinkedIn ↗</a></div></div><div className="terminal"><div className="terminalTop"><span>ANALYTICS WORKFLOW</span><em>● LIVE</em></div>{["Raw Data","Cleaning & Validation","Analysis","Modelling","Dashboard","Business Insight"].map((x,i)=><div className="step" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><i style={{width:`${34+i*11}%`}}/></div>)}<div className="decision"><span>Business question</span><b>→</b><span>Decision-ready insight</span></div></div></div><div className="wrap stats"><div><b>6+</b><span>Projects</span></div><div><b>2+</b><span>Years analytics experience</span></div><div><b>2</b><span>Publications</span></div><div><b>10+</b><span>Certifications</span></div></div></section>
<section id="about"><div className="wrap split"><div><p className="kicker">ABOUT ME</p><h3>Analytics with a business purpose.</h3></div><div><p className="big">I’m an MSc Data Science & Artificial Intelligence candidate at the University of Liverpool with hands-on experience across operational reporting, student-recruitment analysis, business intelligence, financial analysis and predictive modelling.</p><p>I work across the full analytics path: cleaning and validating raw data, structuring analysis, building KPI dashboards, automating recurring reporting, evaluating financial performance and translating findings into recommendations that non-technical stakeholders can use.</p></div></div></section>
<section className="alt"><div className="wrap"><p className="kicker">WHAT I DO</p><h3>Three ways I create value with data.</h3><div className="cards"><article><span>01</span><h4>Data Analysis</h4><p>Clean, validate and analyse complex datasets to uncover patterns, trends and decision-relevant insights.</p></article><article><span>02</span><h4>Business Intelligence</h4><p>Design KPI reporting and interactive dashboards that make performance easier to understand and act on.</p></article><article><span>03</span><h4>Predictive & Financial Analytics</h4><p>Use Python, SQL and financial modelling to explore forecasts, profitability, variance and forward-looking business questions.</p></article></div></div></section>
<section id="experience"><div className="wrap"><p className="kicker">EXPERIENCE</p><h3>Analytics experience across business operations.</h3><div className="timeline"><article><time>JAN 2025 — JUL 2025</time><div><h4>Data Analyst Intern · MyEdBuddy</h4><p>Noida, India · Hybrid</p><ul><li>Collected, cleaned, organised and validated operational and student-enquiry datasets.</li><li>Analysed recruitment demand across source city, study destination, university preference and scholarship categories.</li><li>Built structured Excel reporting and translated enquiry/enrollment information into stakeholder-ready insights.</li></ul></div></article><article><time>APR 2021 — MAR 2023</time><div><h4>Data Analyst (Part-time) · Snehal Enterprises</h4><p>Nagpur, India</p><ul><li>Analysed operational datasets to identify recurring trends, quality issues and performance patterns.</li><li>Used Power Query to streamline recurring reporting and improve consistency.</li><li>Built interactive Power BI dashboards and communicated findings to non-technical stakeholders.</li></ul></div></article></div></div></section>
<section className="alt" id="projects"><div className="wrap"><p className="kicker">FEATURED PROJECTS</p><h3>Evidence, not just a skills list.</h3><p className="intro">Projects are presented as business case studies: problem → data → analysis → output → insight.</p><div className="projects">{projects.map((p,i)=><article className={i<2?"project featured":"project"} key={p.title}>{p.image&&<img src={p.image} alt={`${p.title} dashboard preview`}/>}<div className="projectBody"><span className="tagline">{p.type}</span><h4>{p.title}</h4><p>{p.desc}</p><div className="tags">{p.tools.map(t=><span key={t}>{t}</span>)}</div><div className="links">{p.href&&<Link href={p.href}>View Case Study →</Link>}{p.repo&&<a href={p.repo} target="_blank">GitHub ↗</a>}</div></div></article>)}</div></div></section>
<section id="skills"><div className="wrap"><p className="kicker">SKILLS</p><h3>A practical analytics toolkit.</h3><div className="skillGrid">{skills.map(([a,b])=><article key={a}><h4>{a}</h4><p>{b}</p></article>)}</div></div></section>
<section className="alt"><div className="wrap split"><div><p className="kicker">EDUCATION</p><h3>Technical foundation + applied analytics.</h3></div><div className="education"><article><span>2025 — 2026</span><h4>MSc Data Science & Artificial Intelligence</h4><p>University of Liverpool · United Kingdom</p></article><article><span>2020 — 2025</span><h4>BEng Electronics & Communications Engineering</h4><p>VIT · India</p></article></div></div></section>
<section><div className="wrap"><p className="kicker">CREDENTIALS</p><h3>Selected professional learning.</h3><div className="credentialGrid">{credentials.map((c,i)=><article key={c}><b>{String(i+1).padStart(2,"0")}</b><span>{c}</span></article>)}</div><a className="textLink" href="https://www.linkedin.com/in/ayush-zode-b72020321" target="_blank">View all credentials on LinkedIn ↗</a></div></section>
<section className="alt" id="research"><div className="wrap"><p className="kicker">RESEARCH & PUBLICATIONS</p><h3>Research experience alongside business analytics.</h3><div className="cards two"><article><span>PUBLICATION</span><h4>Verification and Tracking of Humans in Campus</h4><p>Published November 2024. Public link will be added when available.</p></article><article><span>PUBLICATION</span><h4>Massive MIMO Antenna Performance Analysis</h4><p>Published November 2024. Public link will be added when available.</p></article></div></div></section>
<section id="contact"><div className="wrap contact"><div><p className="kicker">CONTACT</p><h3>Have a data problem worth solving?</h3><p>I’m currently based in Liverpool and open to Data Analyst and business-focused analytics opportunities across the UK.</p><div className="contactLinks"><a href="mailto:ayush.s.zode.uk@gmail.com">ayush.s.zode.uk@gmail.com</a><a href="https://github.com/ayushszode" target="_blank">github.com/ayushszode ↗</a><a href="https://www.linkedin.com/in/ayush-zode-b72020321" target="_blank">LinkedIn ↗</a></div></div><form action="https://formsubmit.co/ayush.s.zode.uk@gmail.com" method="POST"><input type="hidden" name="_subject" value="Portfolio contact — ayushszode"/><input type="hidden" name="_captcha" value="false"/><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Message<textarea name="message" rows={5} required/></label><button className="btn" type="submit">Send Message</button></form></div></section>
<footer><div className="wrap"><span>© 2026 Ayush Sanjay Zode</span><span>@ayushszode · Data Analyst</span></div></footer>
</main>}
